<div id="header">
<div id="logo"><img src="/images/sitelogo.gif" border="0" alt="動漫花園資源網" /></div>
<div id="links"><a href="http://share.dmhy.org/">動漫花園資源網</a> | <a
	href="http://share.dmhy.org/">動漫花園分享園</a> | <a
	href="http://share.dmhy.org/">動漫花園新聞頁</a> | <a
	href="http://share.dmhy.org/">動漫花園論壇</a> | <a
	href="http://share.dmhy.org/">求種列表</a> | <a
	href="http://share.dmhy.org/">我要舉報</a> | <a
	href="http://share.dmhy.org/">張貼分享</a> | <a
	href="http://share.dmhy.org/rss.php"> <img src="/images/rss.gif"
	width="36" height="14" border="0" /></a></div>
<div id="search"><input type="text" id="search_keywords" name="kw"
	value="" /> <input type="submit" id="search_button" value="搜索" /></div>
</div>
